ci(check suite): coverage checks (#2)

diff --git a/.github/workflows/check_suite.yml b/.github/workflows/check_suite.yml
--- a/.github/workflows/check_suite.yml
+++ b/.github/workflows/check_suite.yml
@@ -16,6 +16,7 @@ permissions:
 env:
   FORCE_COLOR: 2
   FOUNDRY_PROFILE: ci
+  COVERAGE_SENSITIVITY_PERCENT: 1
 
 jobs:
   # Initial check creation job
@@ -157,7 +158,54 @@ jobs:
           echo "test_output<<EOF" >> $GITHUB_OUTPUT
           cat test_output.txt >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
-      
+
+      - name: Run coverage
+        shell: bash
+        id: forge_coverage
+        run: forge coverage --report summary --report lcov
+
+      - name: Setup LCOV
+        uses: hrishikesh-kadam/setup-lcov@v1
+
+      - name: Filter directories
+        run: lcov --remove lcov.info 'test/*' 'script/*' --output-file lcovNew.info --rc lcov_branch_coverage=1 --rc derive_function_end_line=0 --ignore-errors unused
+
+      - name: Capture coverage output
+        id: new-coverage
+        uses: zgosalvez/github-actions-report-lcov@v3
+        with:
+          coverage-files: lcovNew.info
+
+      - name: Retrieve previous coverage
+        uses: actions/download-artifact@v2
+        with:
+          name: coverage
+          path: coverage.info
+        continue-on-error: true
+
+      - name: Check if a previous coverage exists
+        run: |
+          if [ ! -f coverage.info ]; then
+            echo "Artifact not found. Initializing at 0"
+            echo "0" >> coverage.info
+          fi
+
+      - name: Compare previous coverage
+        run: |
+          old=$(cat coverage.info)
+          new=$(( ${{ steps.new-coverage.outputs.total-coverage }} + ${{ env.COVERAGE_SENSITIVITY_PERCENT }} ))
+          if [ "$new" -lt "$old" ]; then
+            echo "Coverage decreased from $old to $new"
+            exit 1
+          fi
+          mv lcovNew.info coverage.info
+
+      - name: Upload the new coverage
+        uses: actions/upload-artifact@v2
+        with:
+          name: coverage
+          path: coverage.info
+
       - name: Update Check - Complete
         if: always()
         uses: actions/github-script@v6
